### ISSUE TITLE
Several unexpected behavior

### ISSUE THREAD

**Issue by acimail01** [bugsounet/MMM-AssistantMk2#359]
Hello,
I trigger the notification "TRIGGER_PAGES_NEXT_PAGE" (without payload!) to MMM-NotificationTrigger in 2 different ways.
Once via a web service and once from AssistantMk2 via recipe as transcriptionHook.
Then MMM-NotificationTrigger fires "PAGE_INCREMENT".

In the first case, it works wonderfully - 1 page is turned.
In the second case, the page is also scrolled, 
but the content of the MMM-CalenderExt2 appears mysteriously mixed on the following page.

It is not clear whether MMM-Assistantmk2 or MMM-CalendarExt2 is responsible. 
In my opinion, it should be a side effect of the MMM-AssistantMk2, since this behavior does not occur via the web service.

Further:
AssistantMk2 no longer displays the white input GUI to me (ui: 'Fullscreen', position: 'fullscreen_above') and, 
more importantly, 
the screen remains dark for a long time after recognition of a recipe (responseConfig.timer = 5000)

How can you explain that different behavior can occur with identical notification? Is the module name evaluated in AssistantMk2?

**Comment by acimail01** [comment]
1) Keine weiße Input-UI erscheint
2 ) NAch Rezepterkennung lange schwarzer Screen Pause
3) Content wird vermischt (tritt nur in Verbindung mit CalendarExt2 auf)

Video attached in zip.


[mixed_content.zip](https://github.com/bugsounet/MMM-AssistantMk2/files/4456693/mixed_content.zip)

**Comment by eouia** [comment]
Your issue is a too complex mixture of many modules.
If possible, break an issue to several parts then conquer one by one.

You can obsolete MMM-AssistantMk2. Simulate to test notification by MMM-NotificationTrigger webendpoint. (with CURL) So, you need to confirm MMM-NotificationTrigger works as expected.
Then You need to confirm MMM-CalendarExt2 works by those notifications.
After then, you can check MMM-AssistantMk2 has a responsibility or not.

**Comment by acimail01** [comment]
Thank you for your correct advice.
was able to find out that the UI is not displayed due to MMM pages. There is a lack of a good Page module, I tried different ones, each has some disadvantages. I close the issue.
