### ISSUE TITLE
Trying to talk with, but it doesn't recognize any word that I say

### ISSUE THREAD

**Issue by AlexDomtad** [bugsounet/MMM-AssistantMk2#380]
**Describe the problem**
Well, I say "Smart-Mirror" and recognizes de HOTWORD, when passes to the page of assistant, I say words and words, but I hadn't had a response of anything, don't recognize what I say. 

**To Reproduce**
Steps to reproduce the behavior: (Describe what did you do)

**Expected behavior**
I need a response back or just my voice recognized for the program, but just recognize de hotword

**Screenshots**
![s](https://user-images.githubusercontent.com/64671963/80852610-90bd6f80-8bef-11ea-92b7-5947032706b7.png)
![problem](https://user-images.githubusercontent.com/64671963/80852613-96b35080-8bef-11ea-9fff-bb5dfc1b5b4d.png)

In that part stays until it says me "Sorry, I don´t understand"

**Environment:**
 - Device : [e.g. RPI 4b]
 - OS: [e.g. Raspbian buster, the last software]
 - Node Version :
 - Etc.

CODE of module 
{
	module: "MMM-Hotword",
	position: "bottom_right",
	config: {
		chimeOnFinish: null,
		mic: {
			recordProgram: "arecord",
			device: "plughw:1"
		},
		models: [
			{
				hotwords    : "smart_mirror",
				file        : "smart_mirror.umdl",
				sensitivity : "0.5",
			},
		],
		commands: {
			"smart_mirror": {
				notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
					}
				},
				restart:true,
				afterRecordLimit:0
			}
		}
	}
},
{
	module: "MMM-AssistantMk2",
	position: "top_right",
	config: {
		deviceLocation: {
			coordinates: {
				latitude: 37.5650168, // -90.0 - +90.0
				longitude: 126.8491231, // -180.0 - +180.0
			},
		},
		record: {
			recordProgram : "arecord",  
			device        : "plughw:1,0",
		},
		notifications: {
			ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
			ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
		},
		useWelcomeMessage: "brief today",
		profiles: {
			"default" : {
				lang: "en-US"
			}
		},

**Comment by bugsounet** [comment]
hi,

In this cas there many solutions:

1) ~~ask to developer to code program with your simplified `config.js` file~~
2) ~~ask to developer to send you the manual of this module~~
3) ~~tell to developer it's an fake module because it doesn't work~~
4) ~~Send a report of this error to Microsoft Corporation~~
5) Read the [wiki](https://github.com/bugsounet/MMM-AssistantMk2/wiki) because i don't read the [README](https://github.com/bugsounet/MMM-AssistantMk2#mmm-assistantmk2) file

Make your choice,
regards

@bugsounet
